### ISSUE TITLE
500头像获取报错

### ISSUE THREAD

**Issue by ghost** [xfgryujk/blivechat#85] opened 2022-09-29 16:07 UTC
2022-09-30 00:06:32 ERROR [tornado.access]: 500 GET /api/avatar_url?uid=199131172 (111.18.43.253) 52.56ms
2022-09-30 00:06:40 ERROR [tornado.application]: Uncaught exception GET /api/avatar_url?uid=40718200 (111.18.43.253)
HTTPServerRequest(protocol='http', host='远程服务器', method='GET', uri='/api/avatar_url?uid=40718200', version='HTTP/1.0', remote_ip='111.18.43.253')
Traceback (most recent call last):
  File "tornado\web.py", line 1704, in _execute
  File "api\chat.py", line 343, in get
  File "services\avatar.py", line 54, in get_avatar_url_or_none
  File "services\avatar.py", line 141, in _get_avatar_url_from_web_coroutine
  File "services\avatar.py", line 171, in _do_get_avatar_url_from_web
KeyError: 'face'

**Comment by xfgryujk** [comment] 2022-09-30 02:17
Duplicate of #84

**Closed as completed** 2022-10-06 10:12 UTC
