### ISSUE TITLE
关于bilivechat无法获取头像

### ISSUE THREAD

**Issue by fffsfdsf** [xfgryujk/blivechat#100] opened 2023-03-03 17:28 UTC
在w10 22H2使用过windows编译好的端以及尝试过在ubuntu上自编译运行都无法正常使用
ubuntu20.04.5 lts，内核5.15.0-67-generic，python3.82-0ubuntu2
windows下报错

2023-03-03 23:55:53 ERROR [asyncio]: Task exception was never retrieved
future: <Task finished name='Task-39' coro=<LiveMsgHandler.__on_danmaku() done, defined at services\chat.py:284> exception=KeyError('face')>
Traceback (most recent call last):
  File "services\chat.py", line 286, in __on_danmaku
  File "services\avatar.py", line 41, in get_avatar_url
  File "services\avatar.py", line 54, in get_avatar_url_or_none
  File "services\avatar.py", line 141, in _get_avatar_url_from_web_coroutine
  File "services\avatar.py", line 171, in _do_get_avatar_url_from_web
KeyError: 'face'
这时无法获取弹幕以及头像，这个报错在每个弹幕发出后会重复

或者

ERROR 【tornado.access】: 500 GET /api/avatar_url?uid=【我的直播间ID】(127.0.0.1)
这时可以获取弹幕但是没有头像

ubuntu下报错
2023-03-04 01:11:26 INFO [services.avatar]: Failed to fetch avatar: code=-401 非法访问 uid=28528263

2023-03-04 01:12:02 ERROR [services.translate]: TencentTranslateFree init error:

Traceback (most recent call last):

File "/home/fffsfdsf/桌面/blivechat copy/services/translate.py", line 234, in doinit

async with utils.request.http_session.get('<https://fanyi.qq.com/>') as r:

File "/usr/local/lib/python3.8/dist-packages/aiohttp/client.py", line 1117, in aenter

self.*resp = await self.*coro

File "/usr/local/lib/python3.8/dist-packages/aiohttp/client.py", line 619, in _request

break

File "/usr/local/lib/python3.8/dist-packages/aiohttp/helpers.py", line 656, in exit

raise asyncio.TimeoutError from None

asyncio.exceptions.TimeoutError
可以拉取到弹幕但是没有头像
尝试配置过config.ini，仍然没用

尝试使用公共端链接是正常获取到头像和弹幕的
大概是哪里的问题
防火墙没有特别阻拦因为已经在上面跑个人网盘了

**Comment by xfgryujk** [comment] 2023-03-04 06:36
Duplicate of #84

**Closed** 2023-03-08 08:42 UTC
